apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret
  namespace: {{ .Values.namespace }}
spec:
  hostAPI: {{ .Values.secret.hostAPI }}
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: {{ .Values.serviceToken.name }}
        secretNamespace: {{ .Values.namespace }}
      secretsScope:
        envSlug: {{ .Values.serviceToken.envSlug }}
        secretsPath: {{ .Values.serviceToken.secretsPath }}
  managedSecretReference:
    secretName: {{ .Values.secret.managedSecretName }}
    secretNamespace: {{ .Values.namespace }}